### ISSUE TITLE
Traceback (most recent call last):   File "index.py", line 1, in <module> ModuleNotFoundError: No module named 'webview'

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam-Desktop#1]
Traceback (most recent call last):
  File "index.py", line 1, in <module>
ModuleNotFoundError: No module named 'webview'

![image](https://github.com/user-attachments/assets/82b3d11f-9e0d-46e3-aab1-22811a342049)

**Comment by BaseMax** [comment]
![image](https://github.com/user-attachments/assets/036092c2-3925-46ee-9cf8-d44cba9925b0)

**Comment by mohamadreza1388** [comment]
خب این نیاز به یک پکیج داره
باید نصب کنین
پای اینستالر هم باید نصب بشه

**Comment by BaseMax** [comment]
لطفا نام پکیج رو بفرستید.

با زدن دستور
pip install -r requirements.txt

پکیج های مورد نیاز باید نصب بشه من فایل اش رو ساختم
اگه پکیجی هست به فایل اضافه کنید

https://github.com/SalamLang/Salam-Desktop/blob/main/requirements.txt

**Comment by mohamadreza1388** [comment]
نمیدونم اخه چی بود
دنبالش میگردم پیدا کردم خبرتون میکنم

**Comment by BDadmehr0** [comment]
شاید کمکی بکند : https://github.com/Nuitka/Nuitka/issues/2231

**Comment by BaseMax** [comment]
Hi @BDadmehr0,

Thank you so much for your suggestion and the resources you shared! We really appreciate your input. If you're interested, we'd love to have you work on this issue with us. Your help would be invaluable to the project!

Best wishes,
Max

**Comment by BDadmehr0** [comment]
I was trying to run the program when I encountered this error:

``` bash
➜  Salam-Desktop-main python index.py 
[pywebview] GTK cannot be loaded
Traceback (most recent call last):
  File "/home/dadmehr/.pyenv/versions/3.12.6/lib/python3.12/site-packages/webview/guilib.py", line 37, in import_gtk
    import webview.platforms.gtk as guilib
  File "/home/dadmehr/.pyenv/versions/3.12.6/lib/python3.12/site-packages/webview/platforms/gtk.py", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
[pywebview] QT cannot be loaded
Traceback (most recent call last):
  File "/home/dadmehr/.pyenv/versions/3.12.6/lib/python3.12/site-packages/webview/guilib.py", line 49, in import_qt
    import webview.platforms.qt as guilib
  File "/home/dadmehr/.pyenv/versions/3.12.6/lib/python3.12/site-packages/webview/platforms/qt.py", line 24, in <module>
    from qtpy import QtCore
ModuleNotFoundError: No module named 'qtpy'
Traceback (most recent call last):
  File "/home/dadmehr/Documents/GitHub/Salam-Desktop-main/index.py", line 30, in <module>
    webview.start()
  File "/home/dadmehr/.pyenv/versions/3.12.6/lib/python3.12/site-packages/webview/__init__.py", line 166, in start
    guilib = initialize(gui)
             ^^^^^^^^^^^^^^^
  File "/home/dadmehr/.pyenv/versions/3.12.6/lib/python3.12/site-packages/webview/guilib.py", line 124, in initialize
    raise WebViewException(
webview.errors.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.
```

And it seems to have a general [solution](https://github.com/r0x0r/pywebview/issues/805)

I would like to start by preventing this strange error from showing up. It would be better to implement error handling so that instead of an error, it prints a solution.

**Comment by BaseMax** [comment]
@mohamadreza1388 built and tested this repository on a Windows laptop.

If it's too complex and hard - we can build the webview software based on Qt Widgets, I guess all these errors will be solved and Qt will handle all operating systems.
